# Dockerfile para el Backend
# Utiliza una imagen base de Node.js
FROM node:20

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto
COPY package*.json ./
RUN npm install

# Copia el resto de los archivos
COPY . .

# Expone el puerto en el que la aplicación escucha
EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
